### ISSUE TITLE
Fatal crash: Too many arguments provided to core.translate

### ISSUE THREAD

**Issue by crabctrl** [GunshipPenguin/sprint#13]
Using latest commit of hudbars and sprint, on singleplayer 5.0.1

**Comment by BrunoMine** [comment]
I fixed it on my [fork](https://github.com/BrunoMine/sprint)

**Comment by crabctrl** [comment]
I'd recommend making a pull request, but in the meantime I'll use your fork. Thanks!

**Comment by GunshipPenguin** [comment]
Hey, It's been quite awhile since I've worked on Mintest mods. Most of the ones I wrote years ago are pretty stale by now, and as a full-time student, I don't have the time to keep them all updated like I used to. I'd recommend you use @BrunoMine's fork as it's being actively maintained.
