### ISSUE TITLE
hudbars/sprint without move fix

### ISSUE THREAD

**Issue by Ombridride** [GunshipPenguin/sprint#3]
Hi,

hudbars support and fixed the sprint without move, by crabman,

Take a look at here : https://github.com/Ombridride/minetest-minetestforfun-server/commit/e849f33780208e4366fdc2b1003649ce86f7d97c

**Comment by GunshipPenguin** [comment]
Hi
This mod already supports hudbars, as added in #2.
cbd817ff6c3c94cd92280408cbf8b7adacc97859 - Removes sprinting without moving.
