### ISSUE TITLE
Cannot run Sprint mod on Minetest 0.4.14

### ISSUE THREAD

**Issue by CrusoeDaWolf** [GunshipPenguin/sprint#5]
I am running Fedora 24 (x86_64) and I get this error while trying to load up a map:

> 2016-11-19 14:44:42: ERROR[Main]: ModError: Failed to load and run script from /home/ssardiko/.minetest/mods/sprint_mod/init.lua:
> 2016-11-19 14:44:42: ERROR[Main]: /home/ssardiko/.minetest/mods/sprint_mod/init.lua:30: attempt to concatenate a nil value
> 2016-11-19 14:44:42: ERROR[Main]: stack traceback:
> 2016-11-19 14:44:42: ERROR[Main]: 	/home/ssardiko/.minetest/mods/sprint_mod/init.lua:30: in main chunk
> 2016-11-19 14:44:42: ERROR[Main]: Check debug.txt for details.

**Comment by BrunoMine** [comment]
Rejane the folder of the mod to "sprint" only.

**Comment by CrusoeDaWolf** [comment]
Seems to work now, but I can't sprint by double tapping W. I have to press the use key.

**Comment by BrunoMine** [comment]
Open the [minetest.conf](http://wiki.minetest.net/Minetest.conf) file and insert the line below:

`sprint_method = 0`

All possible settings are in the [README.txt](https://github.com/GunshipPenguin/sprint/blob/master/README.md)

**Comment by CrusoeDaWolf** [comment]
Ah. I missed that! Thank you. c:

**Comment by CrusoeDaWolf** [comment]
For some reason, on a couple of maps, sprinting doesn't affect speed at all. :|

**Comment by CrusoeDaWolf** [comment]
For some reason, on a couple of maps, sprinting doesn't affect speed at all. :|

**Comment by BrunoMine** [comment]
This may be related to the normal speed and fast speed of the world.

Anyway, I do not know this helps you solve your problem.

**Comment by CrusoeDaWolf** [comment]
Alright. Thank you anyways!
